### ISSUE TITLE
Fix GHA to use actions-mn actions

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/scc-ab-docs#3]
Depends on:
* https://github.com/actions-mn/build-and-publish/issues/1

**Comment by CAMOBAP** [comment]
Done https://github.com/metanorma/scc-ab-docs/commit/9a0a8cd5e3c48ef6bb331ebefbeb9af9473ab8fb

**Comment by CAMOBAP** [comment]
@ronaldtse the same issue which we had in https://github.com/actions-mn/build-and-publish/pull/2 could you please check that pages enabled in settings?

**Comment by ronaldtse** [comment]
@CAMOBAP you're right, it worked! Let's add this to the README too... apparently the new way of using GH Pages requires a manual setting change.

**Comment by CAMOBAP** [comment]
Note added to Prereq section in readme https://github.com/actions-mn/build-and-publish/blob/main/README.md
